# Installs software-config agents for ubuntu with pip install

parameters:
  image: 61590776-c850-456c-8ab2-8016b6ae4ad5

resource_registry:
  "Heat::InstallConfigAgent": bootconfig_centos_virtialenv.yaml
